-- DDL generated by Postico 1.4.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE study_sets (
    set_id SERIAL PRIMARY KEY,
    title character varying(100) NOT NULL,
    description character varying(100),
    creator_id integer NOT NULL REFERENCES accounts(user_id) ON DELETE CASCADE,
    created timestamp without time zone NOT NULL DEFAULT now(),
    changed timestamp without time zone NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX study_sets_pkey ON study_sets(set_id int4_ops);
