-- DDL generated by Postico 1.4.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE accounts (
    user_id SERIAL PRIMARY KEY,
    username character varying(50) NOT NULL UNIQUE,
    email character varying(355) NOT NULL UNIQUE,
    created timestamp without time zone NOT NULL DEFAULT now(),
    changed timestamp without time zone NOT NULL DEFAULT now(),
    is_deleted boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX accounts_pkey ON accounts(user_id int4_ops);
CREATE UNIQUE INDEX accounts_username_key ON accounts(username text_ops);
CREATE UNIQUE INDEX accounts_email_key ON accounts(email text_ops);
