-- DDL generated by Postico 1.4.4
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE study_terms (
    term_id SERIAL PRIMARY KEY,
    parent_set_id integer NOT NULL REFERENCES study_sets(set_id) ON DELETE CASCADE,
    created timestamp without time zone NOT NULL DEFAULT now(),
    changed timestamp without time zone NOT NULL DEFAULT now(),
    word text NOT NULL DEFAULT ''::text,
    definition text NOT NULL DEFAULT ''::text,
    is_deleted boolean NOT NULL DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX study_terms_pkey ON study_terms(term_id int4_ops);
